### ISSUE TITLE
Gemfury package does not seem to work

### ISSUE THREAD

**Issue by evz** [caravancoop/sfm#6]
I noticed that we have a [Gemfury URL](https://github.com/caravancoop/sfm/blob/dev/requirements.txt#L13-L15) to get the `django-complex-fields` requirement. Just running `pip install -r requirements.txt` yields:

```
 Could not find a version that satisfies the requirement django-complex-fields==0.1.0 (from -r requirements.txt (line 15)) (from versions: )
No matching distribution found for django-complex-fields==0.1.0 (from -r requirements.txt (line 15))
```

which I'm guessing is because that Gemfury URL doesn't seem to have anything on the other end.

**Comment by etiennelatulippe** [comment]
@jpmckinney

**Comment by jpmckinney** [comment]
`complex_fields` is now a public repo, so you can update the dependency to point to the [GitHub repo](https://github.com/caravancoop/complex_fields).

I was only using Gemfury because the repo had been private. No point in debugging if not needed now.

**Comment by evz** [comment]
OK sounds good.
